config/routes.rb
Rails.application.routes.draw do
  root "episodes#index"
  # root "episodes#new_index"
  devise_for :users
  resources :segments
  resources :timestamps do
    member do
      put "vote", to: "timestamps#vote"
    end
  end
  resources :episodes
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/episode.rb
class Episode < ApplicationRecord
  has_many :timestamps, dependent: :destroy

  # def url
  #   "https://traffic.libsyn.com/uhhyeahdude/#{self.filename}.mp3"
  # end

  def short_title
    "Ep " + self.number.to_s
  end

  def title
    "Episode " + self.number.to_s
  end

  def uid
    "ep" + self.number.to_s
  end
end

app/models/segment.rb
class Segment < ApplicationRecord
  has_many :timestamps

  scope :ordered, ->  { order(title: :asc) }
end

app/models/timestamp.rb
class Timestamp < ApplicationRecord
  attr_accessor :hours, :minutes, :seconds

  belongs_to :episode
  belongs_to :segment, optional: true
  belongs_to :user

  acts_as_votable

  def display_time
    Time.at(self.start).utc.strftime("%H:%M:%S")
  end

  def uid
    "ts" + self.id.to_s
  end

  def deletable?
    
  end
end

app/models/user.rb
class User < ApplicationRecord
  acts_as_voter
  
  has_many :timestamps
  
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/episodes_controller.rb
class EpisodesController < ApplicationController
  def index
    @episodes = Episode.order(number: :desc).first(5)
    @top5 = Timestamp.order(cached_votes_total: :desc).first(5)
    @randoms = Timestamp.order("RANDOM()").limit(5)
  end
end

app/controllers/segments_controller.rb
class SegmentsController < ApplicationController
  before_action :set_segment, only: [:show, :edit, :update, :destroy]

  # GET /segments
  # GET /segments.json
  def index
    @segments = Segment.all
  end

  # GET /segments/1
  # GET /segments/1.json
  def show
  end

  # GET /segments/new
  def new
    @segment = Segment.new
  end

  # GET /segments/1/edit
  def edit
  end

  # POST /segments
  # POST /segments.json
  def create
    @segment = Segment.new(segment_params)

    respond_to do |format|
      if @segment.save
        format.html { redirect_to @segment, notice: 'Segment was successfully created.' }
        format.json { render :show, status: :created, location: @segment }
      else
        format.html { render :new }
        format.json { render json: @segment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /segments/1
  # PATCH/PUT /segments/1.json
  def update
    respond_to do |format|
      if @segment.update(segment_params)
        format.html { redirect_to @segment, notice: 'Segment was successfully updated.' }
        format.json { render :show, status: :ok, location: @segment }
      else
        format.html { render :edit }
        format.json { render json: @segment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /segments/1
  # DELETE /segments/1.json
  def destroy
    @segment.destroy
    respond_to do |format|
      format.html { redirect_to segments_url, notice: 'Segment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_segment
      @segment = Segment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def segment_params
      params.require(:segment).permit(:title)
    end
end

app/controllers/timestamps_controller.rb
class TimestampsController < ApplicationController
  before_action :set_timestamp, only: [:show, :edit, :update, :destroy]

  # GET /timestamps
  # GET /timestamps.json
  def index
    @timestamps = Timestamp.all
  end

  # POST /timestamps
  # POST /timestamps.json
  def create
    puts timestamp_params[:hours]
    puts timestamp_params[:minutes]
    puts timestamp_params[:seconds]
    @timestamp = Timestamp.new(timestamp_params)
    @timestamp.start = (timestamp_params[:hours].to_i * 3600) + (timestamp_params[:minutes].to_i * 60) + timestamp_params[:seconds].to_i

    respond_to do |format|
      if @timestamp.save
        format.html { redirect_to root_path }
        format.json { render :show, status: :created, location: @timestamp }
      else
        format.html { render :new }
        format.json { render json: @timestamp.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /timestamps/1
  # PATCH/PUT /timestamps/1.json
  def update
    respond_to do |format|
      if @timestamp.update(timestamp_params)
        format.html { redirect_to @timestamp, notice: 'Timestamp was successfully updated.' }
        format.json { render :show, status: :ok, location: @timestamp }
      else
        format.html { render :edit }
        format.json { render json: @timestamp.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /timestamps/1
  # DELETE /timestamps/1.json
  def destroy
    # TODO: Make sure user is authorized to delete it -- perhaps make some sort
    # of `user_check` method or something
    @timestamp.destroy
    respond_to do |format|
      # format.html { redirect_to timestamps_url, notice: 'Timestamp was successfully destroyed.' }
      format.js { }
    end
  end

  def vote
    @being_liked = nil
    if current_user
      @timestamp = Timestamp.find(params[:id])
      if current_user.liked? @timestamp
        @timestamp.unliked_by current_user
        @being_liked = false
      else
        @timestamp.liked_by current_user
        @being_liked = true
      end
    else
      # TODO: Add request to sign up or sign in
    end

    respond_to do |format|
      format.js { }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_timestamp
      @timestamp = Timestamp.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def timestamp_params
      params.require(:timestamp).permit(:start, :comment, :episode_id, :segment_id, :hours, :minutes, :seconds)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/episodes_helper.rb
module EpisodesHelper
end

app/helpers/segments_helper.rb
module SegmentsHelper
end

app/helpers/timestamps_helper.rb
module TimestampsHelper
end

app/views/episodes/_episode.html.haml
%audio{src: "#{episode.url}", title: "#{episode.number}", data: { artist: "#{episode.datestring}" }}

%ul
  = render partial: episode.timestamps, locals: {episode: episode}

app/views/episodes/_episode_old.html.haml
%h2.ep-title= episode.title
%audio.uyd-audio{id: "#{episode.uid}", controls: ""}
  %source{src: "#{episode.url}"}
    Can't play it!
-# - @timetstamps = episode.timestamps
= render partial: "timestamps/form", locals: {episode: episode}
= render partial: episode.timestamps, locals: {episode: episode}

app/views/episodes/index.html.haml
-# %nav.navbar.navbar-expand-lg.navbar-light.bg-light
-#   %a.navbar-brand{href: "#"} Uhh Yeah Timestamps
-#   %button.navbar-toggler{"aria-controls" => "navbarSupportedContent", "aria-expanded" => "false", "aria-label" => "Toggle navigation", "data-target" => "#navbarSupportedContent", "data-toggle" => "collapse", :type => "button"}
-#     %span.navbar-toggler-icon
-#   #navbarSupportedContent.collapse.navbar-collapse
-#     %ul.navbar-nav.mr-auto
-#       %li.nav-item.active
-#         %a.nav-link{href: "#"}
-#           %span.sr-only (current)
-#       %li.nav-item
-#         %a.nav-link{href: "https://www.uhhyeahdude.com"} UYD
-#       %li.nav-item
-#         %a.nav-link{href: "https://www.patreon.com/UHHYEAHDUDE"} Support UYD on Patreon
-#       %li.nav-item.dropdown
-#         %a#navbarDropdown.nav-link.dropdown-toggle{"aria-expanded" => "false", "aria-haspopup" => "true", "data-toggle" => "dropdown", :href => "#", :role => "button"}
-#           Segments
-#         .dropdown-menu{"aria-labelledby" => "navbarDropdown"}
-#           - Segment.all.pluck(:id, :title).each do |id, title|
-#             = link_to title, segment_path(id), class: 'dropdown-item'
-#     %form.form-inline.my-2.my-lg-0
-#       %input.form-control.mr-sm-2{"aria-label" => "Search", :placeholder => "Search", :type => "search"}/
-#       %button.btn.my-2.my-sm-0{:type => "submit"} Search

.jumbotron.pt-1.no-background
  %h1.display-4 Uhh Yeah Timestamps
  %p.lead America through the eyes of two American-Americans, through timestamps on this website
  %hr.my-4/
  %p It uses utility classes for typography and spacing to space content out within the larger container.
  %p.lead
    %a.btn.btn-primary.btn-lg{:href => "#", :role => "button"} Learn more

app/views/episodes/old_index.html.haml
- if current_user
  %a{href: destroy_user_session_path, method: :delete} Sign out
  = current_user
  = current_user.id
- else
  %a{href: new_user_registration_path} Sign up
  |
  %a{href: new_user_session_path, method: :get} Sign in
.general-info
  .title Uhh Yeah Timestamps
  .subtitle America through the eyes of two American-Americans,
  .subtitle through timestamps on this website
  .links
    %a{href: "https://uhhyeahdude.com", target: "_blank"}uhhyeahdude.com
    |
    %a{href: "tel:+8888422357"}<
      %i.fa.fa-phone.phone>
      (888) 842-2357
    |
    %a{href: "https://www.patreon.com/UHHYEAHDUDE", target: "_blank"}Support Uhh Yeah Dude on Patreon
%hr
.content
  .top-content
    .half
      %h2 Top 5
      - @top5.each do |t|
        .top5-item
          = t.episode.short_title
          \-
          = t.comment
    .half
      %h2 A few random ones
      - @randoms.each do |t|
        -# Move this to a partial
        .top5-item
          = t.episode.short_title
          \-
          = t.comment


  = render partial: @episodes

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %link{href: "https://fonts.googleapis.com/css?family=Roboto+Slab", rel: "stylesheet", type: "text/css" }
    %title Uhh Yeah Timestamps
    = csrf_meta_tags
    = csp_meta_tag
    = javascript_include_tag 'picobel.min.js'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = stylesheet_link_tag    'player.skeleton.css'
    // = javascript_include_tag :defaults
  %body
    = yield
%hr
.seatbelts Seatbelts.

:javascript  
  Picobel( { theme: 'skeleton' } );

app/views/segments/_form.html.haml
= form_for @segment do |f|
  - if @segment.errors.any?
    #error_explanation
      %h2= "#{pluralize(@segment.errors.count, "error")} prohibited this segment from being saved:"
      %ul
        - @segment.errors.full_messages.each do |message|
          %li= message

  .field
    = f.label :title
    = f.text_field :title
  .actions
    = f.submit 'Save'

app/views/segments/edit.html.haml
%h1 Editing segment

= render 'form'

= link_to 'Show', @segment
\|
= link_to 'Back', segments_path

app/views/segments/index.html.haml
%h1 Listing segments

%table
  %thead
    %tr
      %th Title
      %th
      %th
      %th

  %tbody
    - @segments.each do |segment|
      %tr
        %td= segment.title
        %td= link_to 'Show', segment
        %td= link_to 'Edit', edit_segment_path(segment)
        %td= link_to 'Destroy', segment, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Segment', new_segment_path

app/views/segments/new.html.haml
%h1 New segment

= render 'form'

= link_to 'Back', segments_path

app/views/segments/show.html.haml
%p#notice= notice

%p
  %b Title:
  = @segment.title

= link_to 'Edit', edit_segment_path(@segment)
\|
= link_to 'Back', segments_path

app/views/timestamps/_form.html.haml
= form_with model: Timestamp.new, class: "timestamp-form", id: "#{episode.uid}-timestamp-form" do |f|
  %span
    = f.label "Add a timestamp at "
    %span.time-input<
      = (f.number_field :hours, min: 0, max: 1, step: 1, only_integer: true, id: "#{episode.uid}-hours") + ":"
      = (f.number_field :minutes, min: 0, max: 59, step: 1, id: "#{episode.uid}-minutes", required: true) + ":"
      = f.number_field :seconds, min: 0, max: 59, step: 1, id: "#{episode.uid}-seconds", required: true
      %span.current-time{id: "#{episode.uid}-current-time"} current time

    = f.collection_select :segment_id, Segment.ordered, :id, :title, prompt: "Select a recurring segment (or not)"
    = f.text_field :comment, placeholder: "Short description", required: true
    = f.hidden_field :episode_id, value: episode.id
    = f.hidden_field :start
    = f.submit "✔"

  :javascript
    document.getElementById("#{episode.uid}-current-time").addEventListener("click", function() {
      epAudio = document.getElementById("#{episode.uid}");
      startSeconds = epAudio.currentTime;
      hours = Math.floor(startSeconds / 3600);
      startSeconds %= 3600;
      minutes = Math.floor(startSeconds / 60);
      seconds = Math.floor(startSeconds % 60);
      document.getElementById("#{episode.uid}-hours").value = hours
      document.getElementById("#{episode.uid}-minutes").value = rjust(minutes.toString(), 2, "0")
      document.getElementById("#{episode.uid}-seconds").value = rjust(seconds.toString(), 2, "0")
    })

app/views/timestamps/_timestamp.html.haml
%li
  %span
    = timestamp.display_time
    - if timestamp.segment
      \-
      %strong= timestamp.segment.title
    \-
    %span.comment= timestamp.comment

app/views/timestamps/_timestamp_old.html.haml
%p.timestamp
  %span{id: "#{timestamp.uid}"}
    = timestamp.display_time
    - if timestamp.segment
      \-
      %strong= timestamp.segment.title
    \-
    %span.comment= timestamp.comment
  %span.vote
    - if user_signed_in?
      - if current_user.liked? timestamp
        = link_to vote_timestamp_path(timestamp), id: "#{timestamp.uid}-vote", remote: true, method: :put do
          %i.fa.fa-thumbs-up
          %span.vote-count{id: "#{timestamp.uid}-count"}= timestamp.votes_for.count
      - else
        = link_to vote_timestamp_path(timestamp), id: "#{timestamp.uid}-vote", remote: true, method: :put do
          %i.fa.fa-thumbs-o-up
          %span.vote-count{id: "#{timestamp.uid}-count"}= timestamp.votes_for.count
    - else
      %a{id: "#{timestamp.uid}-vote"}
        -# TODO: Add a hover thing that says "Log in to vote!"
        %i.fa.fa-thumbs-up
        %span.vote-count{id: "#{timestamp.uid}-count"}= timestamp.votes_for.count
  - if user_signed_in? && timestamp.user == current_user
    %span.delete
      = link_to timestamp_path, remote: true, method: :delete, confirm: "Are you sure you want to delete this?" do
        %i.fa.fa-times

:javascript
  time = document.getElementById("#{timestamp.uid}")
  time.addEventListener("click", function() {
    uyd = document.getElementById("#{timestamp.episode.uid}")
    uyd.currentTime = #{timestamp.start}
  })

app/views/timestamps/_top5_timestamp.html.haml
%p.timestamp
  %span{id: "#{timestamp.uid}"}
    = timestamp.display_time
    - if timestamp.segment
      \-
      %strong= timestamp.segment.title
    \-
    %span.comment= timestamp.comment
    \-
  %span.vote
    - if current_user.liked? timestamp
      = link_to vote_timestamp_path(timestamp), id: "#{timestamp.uid}-vote", remote: true, method: :put do
        %i.fa.fa-thumbs-up
        %span.vote-count{id: "#{timestamp.uid}-count"}= timestamp.votes_for.count
    - else
      = link_to vote_timestamp_path(timestamp), id: "#{timestamp.uid}-vote", remote: true, method: :put do
        %i.fa.fa-thumbs-o-up
        %span.vote-count{id: "#{timestamp.uid}-count"}= timestamp.votes_for.count

app/views/timestamps/destroy.js.erb
console.log(this)

app/views/timestamps/edit.html.erb
<h1>Editing Timestamp</h1>

<%= render 'form', timestamp: @timestamp %>

<%= link_to 'Show', @timestamp %> |
<%= link_to 'Back', timestamps_path %>

app/views/timestamps/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Timestamps</h1>

<table>
  <thead>
    <tr>
      <th>Start</th>
      <th>Comment</th>
      <th>Episode</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @timestamps.each do |timestamp| %>
      <tr>
        <td><%= timestamp.start %></td>
        <td><%= timestamp.comment %></td>
        <td><%= timestamp.episode %></td>
        <td><%= link_to 'Show', timestamp %></td>
        <td><%= link_to 'Edit', edit_timestamp_path(timestamp) %></td>
        <td><%= link_to 'Destroy', timestamp, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Timestamp', new_timestamp_path %>

app/views/timestamps/like.js.erb
id = "<%= @timestamp.uid %>" + "-votes"
document.getElementById(id).innerHTML = <%= @timestamp.votes_for.count %>

app/views/timestamps/new.html.erb
<h1>New Timestamp</h1>

<%= render 'form', timestamp: @timestamp %>

<%= link_to 'Back', timestamps_path %>

app/views/timestamps/unlike.js.erb
id = "<%= @timestamp.uid %>" + "-votes"
document.getElementById(id).innerHTML = <%= @timestamp.votes_for.count %>

app/views/timestamps/vote.js.erb
vote = document.getElementById("<%= @timestamp.uid %>-vote")
if (<%= @being_liked %>) {
  vote.children[0].classList.remove("fa-thumbs-o-up")
  vote.children[0].classList.add("fa-thumbs-up")
} else {
  vote.children[0].classList.remove("fa-thumbs-up")
  vote.children[0].classList.add("fa-thumbs-o-up")
}

vote.children[1].innerHTML = <%= @timestamp.votes_for.count %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>